version: "3.3"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:15.0.1
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2